services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  nestjs-app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URI=mongodb://root:example@mongodb:27017/test?authSource=admin
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
    driver: bridge
