name: Composite Action
description: A composite action to build Laravel applications
inputs:
  node-version:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }} # or the version you are using

    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Cache the app dependencies
      uses: actions/cache@v4.0.2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-app