name: "OWASP ZAP scan"
on: workflow_call
jobs:
  build:
    name: Testing ZAP
    runs-on: ubuntu-latest
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        target: 'https://dis03.dexon-technology.com:8089/'
        # target: 'https://privategamehost.com:443/'
        