name: "OWASP ZAP scan"
on:   
  workflow_call:
    secrets:
      PAT:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: VSUS-02

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        token: ${{ secrets.PAT }}
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        target: 'https://privategamehost.com:6444/'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
        retention-days: 1