name: "Test Next App"

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  build:
    name: Testing Workflow
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env: 
          MONGO_INITDB_ROOT_USERNAME: root 
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/prepare-action
        with:
          node-version: ${{ inputs.node-version }}

      - name: Wait for MongoDB to be ready
        run: |
          until nc -zv 127.0.0.1 27017; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
        shell: bash

      - name: Test the App
        run: |
          export PORT=3000
          export DATABASE_URI=mongodb://root:example@localhost:27017/test?authSource=admin
          timeout 10s pnpm test || true
